#!/bin/sh

## Copyright (C) 2014  Luca Saiu
## Updated in 2016 by Luca Saiu
## Written by Luca Saiu

## This file is part of GNU epsilon.

## GNU epsilon is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.

## GNU epsilon is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.

## You should have received a copy of the GNU General Public License
## along with GNU epsilon.  If not, see <http://www.gnu.org/licenses/>.


## I wrote this simple ad-hoc script from scratch instead of reusing
## git-version-gen from GNUlib, which is very sensitive to tag names.

## In this version .tarball-version is supposed to be written manually.

git_command_line='git describe --long --always --all --dirty'
#git_command_line='git describe --always --dirty --tags'
export git_command_line

# The output has no trailing newline: it's intended to be used from m4.

if test -e .tarball-version; then
  if test -e .version \
     && $git_command_line > /dev/null 2> /dev/null \
     && test "$($git_command_line)" != "$(cat .version)"; then
    echo 'ERROR: you should update or delete .tarball-version' 2> /dev/stderr
    exit 1
  else
    printf "%s" "$(cat .tarball-version)"
  fi
elif $git_command_line > .version 2> /dev/null ; then
  printf "git-%s" "$(cat .version)"
else
  echo 'unknown' > .version
  printf "%s" "$(cat .version)"
fi
